$(document).ready(function(){
    $("#btn1").click(function(){
        $("#elemento1").fadeIn();
    });
});
$(document).ready(function(){
    $("#btn2").click(function(){
        $("#elemento2").fadeOut();
    });
});
$(document).ready(function(){
    $("#btn3").click(function(){
        $("#box").animate({height:"200px"});
    });
    $("#btn4").click(function(){
        $("#box").animate({height:"100px"});
    });
});
$(document).ready(function(){
    $("#btn5").click(function(){
        $("#elemento3").delay("fast").fadeIn();
    });
});
